name: "export-unpack-commit"
description: "Export, unpack, and commit a Power Platform solution"
inputs:
  message:
    description: Message to use for the commit
    required: true

  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: true

  app-id:
    description: 'The application id to authenticate with. Setting this input makes app-id, tenant-id and client-secret required; specifying alternate "username" credential set of inputs will result in an error.'
    required: false

  client-secret:
    description: "The client secret to authenticate with. Required if authenticating with app-id."
    required: false

  tenant-id:
    description: "Tenant id if using app-id & client secret to authenticate."
    required: false

  solution-name:
    description: "Name of solution to export"
    required: true

runs:
  using: composite
  steps:
    - uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.app-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ inputs.tenant-id }}
        solution-output-file: ${{ inputs.solution-name }}.zip
        solution-name: ${{ inputs.solution-name }}
    - uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.app-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ inputs.tenant-id }}
        solution-output-file: ${{ inputs.solution-name }}_managed.zip
        solution-name: ${{ inputs.solution-name }}
        managed: true
    - name: Clear existing solution folder
      run: |
        rm -rf solutions/${{ inputs.solution-name }}/src
      shell: bash
    - uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ inputs.solution-name }}.zip
        solution-folder: solutions/${{ inputs.solution-name }}/src
        solution-type: Both
    - uses: EndBug/add-and-commit@v8
      with:
        message: ${{ inputs.message }}
