name: CI / CD

on:
  push:
    paths:
      - solutions/**
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pack con_core
        uses: ./.github/actions/pack-solution
        with:
          name: con_core
      - name: pack con_admissions
        uses: ./.github/actions/pack-solution
        with:
          name: con_admissions
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solutions
          path: packed-solutions
  deploy:
    environment: production
    if: ${{ github.ref_name == 'main' }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: packed-solutions
      - name: Import con_core
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: con_core_managed.zip
      - name: Import con_admissions
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: con_admissions_managed.zip
